

name: Github Pages Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'intlayer/intlayer-home'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.4.0'

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          permissions:
          contents: write 
          pages: write
          id-token: write

      - name: Run install
        run: pnpm install 

      - name: Build for production
        run: pnpm build

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./public
          cname: intlayer.io
